mysite/food/urls.py
from . import views
from django.urls import path

app_name = 'food'

urlpatterns = [
    # index-page
    path('',views.IndexClassView.as_view(),name = 'index'),

    path('item/',views.item,name="item"),
    # details-page
    path('detail/<int:pk>/',views.FoodDetail.as_view() , name="detail"),
    # add items
    path('add',views.CreateItem.as_view(),name ="create_item"),
    # edit item
    path('update/<int:id>/',views.update_item,name='update_item'),
    #delete item
    path('delete/<int:id>/',views.delete_item,name = "delete_item"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
og
from users.views import custom_logout
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('food.urls')),
    path('register/',user_views.register, name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name ='users/login.html'),name='login'),
    path('logout/',custom_logout,name='logout'),
    path('profile/',user_views.profilepage,name = 'profile'),
]



urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.urls import reverse

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.Item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    Item_name = models.CharField(max_length=200)
    Item_desc = models.CharField(max_length=200)
    Item_Price = models.IntegerField()
    Item_image = models.CharField(max_length=500,default='https://cookinupastorm.biz/wp-content/uploads/2023/04/EmptyDinnerPlates.jpg')

    def get_absolute_url(self):
        return reverse('food:detail',kwargs={'pk':self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['Item_name','Item_desc','Item_Price','Item_image']

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

mysite/food/views.py
from tempfile import template

from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import ItemForm
from .models import Item
from django.views.generic import ListView, DetailView, CreateView


# Create your views here.
# function based view
#
def index(request):
    Item_list =  Item.objects.all()
    print(Item_list)
    # context =
    return render(request,'food/index.html',{"Item_lists": Item_list})


# class-based view
class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'Item_lists'

def item(request):
    return HttpResponse("<h1>Maximum effort</h1>")

# fun-based view

def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context = {
        "item" : item
    }
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

#     fun-based view
#
def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item_form.html',{'form':form})

# classs-based create view
#
class CreateItem(CreateView):
    model = Item
    fields = ['Item_name','Item_desc','Item_Price','Item_image']
    template_name = 'food/item_form.html'
    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)



def update_item(request,id):
    item = Item.objects.get(id = id)
    form = ItemForm(request.POST or None, instance = item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item_form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id = id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request,'food/delete_item.html',{'item':item})

mysite/users/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import RegistrationForm


# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'welcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request,'users/register.html',{'form':form})

def custom_logout(request):
    logout(request)
    return render(request,'users/logout.html')
@login_required
def profilepage(request):
    return render(request,'users/profile.html')

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>

<nav class="navbar navbar-dark bg-danger">
    <a href="#" class="navbar-brand">Food App</a>
    <div class="navbar">
        <a class="nav-item nav-link"  href="#" style="margin-left:5px;"> Menu Item </a>
        <a class="nav-item nav-link"  href="{% url 'food:create_item' %}" style="margin-left:5px;"> Add Item </a>
        <a class="nav-item nav-link"  href="#" style="margin-left:5px;"> Delete Item </a>
        <a class="nav-item nav-link"  href="" style="margin-left:5px;"> Update Item </a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" style="margin-left:5px;" class="nav-item nav-link">logout</a>
            <a href="{% url 'profile' %}" style="margin-left:5px;" class="nav-item nav-link">Profile</a>
        {% else %}
            <a href="{% url 'login' %}" style="margin-left:5px;" class="nav-item nav-link">Login</a>
        {% endif %}
    </div>
</nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tag }}"> {{ message }} </div>

        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/food/templates/food/delete_item.html
<form  method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.Item_name }}</h2>
    <button type="submit" >confirm</button>
</form>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <img src="{{item.Item_image}}" height="300px;" width="200px;" object-fit="cover;" class="card"  />
            </div>
            <div class="col-md-6">
                <h1>{{ object.Item_name }}</h1>

                <h2>{{ object.Item_desc }}</h2>
                <h3>${{ object.Item_Price }}</h3>
                <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>



    {% endblock %}
</body>
</html>

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>

</head>
<body>

    {% block body %}
    {% for item in Item_lists %}

        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px;" width="100%;" object-fit="cover;" src="{{ item.Item_image }}"/>
            </div>
            <div class="col-md-4">
                <h3>{{item.Item_name}}</h3>
                <h5>{{item.Item_name}}</h5>
                <h6>${{item.Item_Price}}</h6>
                <h6>{{ item.user_name }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a><br>
                <a href="{% url 'food:update_item' item.id %}" class="btn btn-primary">Update</a>
            </div>
        </div>

    {% endfor %}
    {% endblock %}


<!--    old code-->

<!--    <ul>-->
<!--        <li>-->
<!--            <a href="{% url 'food:detail' item.id %}">{{item.id}}&#45;&#45;{{item.Item_name}}</a>-->
<!--        </li>-->
<!--    </ul>-->

</body>
</html>

mysite/food/templates/food/item_form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info text-white ">
          <div class="card-title">Add Item</div>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                {{ field.name }}
                <br>
                {{field}}
                <div class="form-group mb-3" ></div>
                {% endfor %}
                <button type="submit" class="btn btn-info" >Save</button>
            </form>

        </div>
      </div>
    </div>
  </div>
</div>





{% endblock %}

mysite/users/templates/users/login.html
{% extends 'food/base.html' %}


{% block body %}

<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info text-white ">
          <div class="card-title">Login</div>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group mb-3">
                  {{ field.name }}
                  {{ field }}
                </div>
            {% endfor %}
            <button class="btn btn-info" type="submit">Login</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

mysite/users/templates/users/logout.html
<!--<form action="{% url 'logout' %}" method="POST">-->
<!--    {% csrf_token %}-->
<!--    <button type="submit">Logout</button>-->
<!--</form>-->
<h1>You have been logout.</h1>

mysite/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width="150px" height="150px" src="{{ user.profile.image.url }}" >

mysite/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}


<div class="container mt-5">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info text-white ">
          <div class="card-title">Register</div>
        </div>
        <div class="card-body">
            <form method="POST" >
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group mb-3" >
                        {{ field.name }}
                        <br>
                        {{ field }}
                    </div>
                {% endfor %}
                <button type="submit"  class="btn btn-info" >Signup</button>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>









{% endblock %}